[project]
name = "northwind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8.1,<3.13"
dependencies = [
    "dlt[motherduck]>=1.5.0",
    "sqlmesh[web]>=0.150.1",
]
