[project]
name = "northwind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "dlt-init-openapi>=0.1.0",
    "dlt[motherduck]>=0.4.12",
    "sqlmesh[web]>=0.141.1",
]
